### ISSUE TITLE
Support env var sytax for Craft 3.1

### ISSUE THREAD

**Issue by timkelty** [putyourlightson/craft-amazon-ses#4]
Craft 3.1 will have a `Craft::parseEnv()` method to parse `$MY_ENV_VAR` from settings. Would be great to support this for region, key, secret settings here.

**Comment by putyourlightson** [comment]
Yes, will be adding compatibility with Craft 3.1 as soon as the stable version arrives, thanks!

**Comment by michaelroper** [comment]
Hey Ben - any chance you have a seperate branch with this supported? It's the only thing stopping me from using `project.yaml` on my site... >_<

**Comment by putyourlightson** [comment]
Hi Michael, I'll be looking into adding this next week. You can of course still use `project.yaml` on your site along with this plugin, since these are plugin settings it will "just work"!

**Comment by michaelroper** [comment]
Thanks Ben - the issue was more that I don't want my AWS key/secret values being output into the `project.yaml` file, because I don't want them to be in my repo. If the fields are supporting the native ENV settings feature, then it will just output the `$MY_ENV_VAR` as the value instead.

But no huge rush, I decided to just remove my key/secret settings for now and go without email, because my site is still in development.

**Comment by putyourlightson** [comment]
Ok, added a new branch (https://github.com/putyourlightson/craft-amazon-ses/tree/v1.1), let me know if there are any issues.

    composer require putyourlightson/craft-amazon-ses:dev-v1.1

**Comment by putyourlightson** [comment]
Added in version 1.1.0.
